export const SET_DETAIL_SINGERID = 'SET_DETAIL_SINGERID'

export const SET_DETAIL_SINGERNAME = 'SET_DETAIL_SINGERNAME'

export const SET_DETAIL_PICURL = 'SET_DETAIL_PICURL'

export const SET_DETAIL_PLAYLIST = 'SET_DETAIL_PLAYLIST'

export const SET_DETAIL_TOPLIST = 'SET_DETAIL_TOPLIST'

// 设置播放器内核页面数据
export const SET_PLAYER_PICURL = 'SET_PLAYER_PICURL'

export const SET_PLAYER_LIST = 'SET_PLAYER_LIST'

export const SET_PLAYER_REALLYLIST = 'SET_PLAYER_REALLYLIST'

export const SET_PLAYER_FULLSCREEN = 'SET_PLAYER_FULLSCREEN'

export const SET_PLAYER_LYRIC = 'SET_PLAYER_LYRIC'

export const SET_PLAYER_CURRENTINDEX = 'SET_PLAYER_CURRENTINDEX'

export const SET_PLAYER_ISPLAY = 'SET_PLAYER_ISPLAY'
